export const ADD_ADVENTURE_TO_CART = "ADD_ADVENTURE_TO_CART";
export const ADD_CLASSIC_TO_CART = "ADD_CLASSIC_TO_CART";
export const ADD_DETECTIVE_TO_CART = "ADD_DETECTIVE_TO_CART";
export const ADD_PHILOSOPHY_TO_CART = "ADD_PHILOSOPHY_TO_CART";
export const ADD_POEM_TO_CART = "ADD_POEM_TO_CART";
export const ADD_PSYCHOLOGY_TO_CART = "ADD_PSYCHOLOGY_TO_CART";
export const ADD_ROMANCE_TO_CART = "ADD_ROMANCE_TO_CART";
export const ADD_SCIENCE_TO_CART = "ADD_SCIENCE_TO_CART";
export const ADD_THRILLER_TO_CART = "ADD_THRILLER_TO_CART";
export const ADD_BOOKS_TO_CART = "ADD_BOOKS_TO_CART"

export const ADD_ADVENTURE_TO_LIST = "ADD_ADVENTURE_TO_LIST";
export const ADD_CLASSIC_TO_LIST = "ADD_CLASSIC_TO_LIST";
export const ADD_DETECTIVE_TO_LIST = "ADD_DETECTIVE_TO_LIST";
export const ADD_PHILOSOPHY_TO_LIST = "ADD_PHILOSOPHY_TO_LIST";
export const ADD_POEM_TO_LIST = "ADD_POEM_TO_LIST";
export const ADD_PSYCHOLOGY_TO_LIST = "ADD_PSYCHOLOGY_TO_LIST";
export const ADD_ROMANCE_TO_LIST = "ADD_ROMANCE_TO_LIST";
export const ADD_SCIENCE_TO_LIST = "ADD_SCIENCE_TO_LIST";
export const ADD_THRILLER_TO_LIST = "ADD_THRILLER_TO_LIST";
export const ADD_BOOKS_TO_LIST = "ADD_BOOKS_TO_LIST";


export const RESET_CART = 'RESET_CART';
export const RESET_LIST = "RESET_LIST";

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const REMOVE_FROM_LIST = 'REMOVE_FROM_LIST';